apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: password-generator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gezibash/challenge-01-apps.git
    targetRevision: HEAD
    path: charts
    helm:
      valueFiles:
        - values.yml
      releaseName: password-generator
      version: v0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  wait: true
