apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-apps
  namespace: argocd
spec:
  generators:
    - directory:
        path: monitoring
        requeueAfterSeconds: 30
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/gezibash/challenge-01-apps.git
        targetRevision: HEAD
        path: apps/monitoring/{{path.basename}}
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
